<a href="https://colab.research.google.com/github/saifharis/Noor/blob/main/NN_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense, Activation, BatchNormalization
import tensorflow as tf
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer 
from sklearn.model_selection import train_test_split
from keras.layers import Dense
from keras.models import Sequential 
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from keras.callbacks import EarlyStopping
from sklearn.preprocessing import scale
from keras.layers import BatchNormalization
from keras.regularizers import l1,l2,l1_l2
from keras import optimizers
from sklearn.linear_model import Lasso
from sklearn.decomposition import PCA
import random


In [ ]:
# load the dataset
dataset =np.loadtxt('UN_nn_model.csv', delimiter=';')
# split into input (X) and output (y) variables
X = dataset[:,0:7]
y = dataset[:,7:10]
print(X,y)

[[-1.50200000e+00  1.44700000e+01  4.87271800e+00  2.18000000e+02
   7.90000000e+01  2.11457026e+02  3.40000000e-01]
 [-1.87200000e+00  7.10000000e+00  4.61762400e+00  2.47000000e+02
   1.42000000e+02  3.57492639e+02  3.30000000e-01]
 [-1.47800000e+00  1.42000000e+01  4.94138932e+00  1.54000000e+02
   9.10000000e+01  2.28075949e+02  2.50000000e-01]
 [-1.30600000e+00  1.44470000e+01  4.86867200e+00  1.45000000e+02
   8.00000000e+01  2.02718447e+02  2.70000000e-01]
 [-1.16300000e+00  6.15000000e+00  4.12493000e+00  3.19000000e+02
   1.65000000e+02  4.22205882e+02  2.79411765e-01]
 [-6.55000000e-01  6.15000000e+00  4.14728469e+00  1.81000000e+02
   8.70000000e+01  2.24957143e+02  2.92857143e-01]
 [-1.03400000e+00  1.49700000e+01  4.42264600e+00  3.27000000e+02
   1.27000000e+02  3.37329422e+02  3.28068592e-01]
 [-1.76400000e+00  1.17900000e+01  5.17583200e+00  1.79000000e+02
   8.80000000e+01  2.26828800e+02  2.90000000e-01]
 [-1.90900000e+00  5.34000000e+00  4.25353400e+00  2.59000000e+0

In [ ]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.3,random_state=None)
print(y_test)

[[ 2.7e-06 -1.4e-02  5.3e+01]
 [-6.4e-06  1.2e-02  2.9e-01]
 [-2.6e-05  8.7e-02 -1.6e+00]]


In [ ]:
model=Sequential()
#, kernel_regularizer=l2(0.07)
model.add(Dense(100, activation='relu', input_dim=7, name='Input_Layer'))
model.add(BatchNormalization(name='1st_Normalization_Layer'))
model.add(Dense(100, activation='relu', name='1st_Hidden_Layer'))
model.add(BatchNormalization(name='2nd_Normalization_Layer'))
model.add(Dense(3))
#model summary
model.summary()

Model: "sequential_14"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input_Layer (Dense)          (None, 100)               800       
_________________________________________________________________
1st_Normalization_Layer (Bat (None, 100)               400       
_________________________________________________________________
1st_Hidden_Layer (Dense)     (None, 100)               10100     
_________________________________________________________________
2nd_Normalization_Layer (Bat (None, 100)               400       
_________________________________________________________________
dense_12 (Dense)             (None, 3)                 303       
Total params: 12,003
Trainable params: 11,603
Non-trainable params: 400
_________________________________________________________________


In [ ]:
#compiling
adam=optimizers.Adam(lr=0.0001)
model.compile(optimizer=adam, loss='mean_squared_error', metrics=['accuracy'])


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
#callback for self-validation will stop training after val_score stops improving for two successive epochs
#early_stopping_monitor=EarlyStopping(patience=10)

#fitting

model_training=model.fit(X_train,y_train, epochs=150, batch_size=10, validation_data=(X_test, y_test))

Epoch 1/150
1/1 [==============================] - 2s 2s/step - loss: 150.6529 - accuracy: 0.3333 - val_loss: 316.8567 - val_accuracy: 0.6667
Epoch 2/150
1/1 [==============================] - 0s 28ms/step - loss: 149.7838 - accuracy: 0.3333 - val_loss: 296.8959 - val_accuracy: 0.6667
Epoch 3/150
1/1 [==============================] - 0s 27ms/step - loss: 148.9030 - accuracy: 0.3333 - val_loss: 292.6153 - val_accuracy: 0.6667
Epoch 4/150
1/1 [==============================] - 0s 27ms/step - loss: 147.7199 - accuracy: 0.3333 - val_loss: 291.3634 - val_accuracy: 0.6667
Epoch 5/150
1/1 [==============================] - 0s 33ms/step - loss: 145.4400 - accuracy: 0.5000 - val_loss: 291.3350 - val_accuracy: 0.6667
Epoch 6/150
1/1 [==============================] - 0s 31ms/step - loss: 143.0443 - accuracy: 0.3333 - val_loss: 291.7798 - val_accuracy: 0.6667
Epoch 7/150
1/1 [==============================] - 0s 30ms/step - loss: 142.5213 - accuracy: 0.3333 - val_loss: 292.2756 - val_accuracy: 0

In [ ]:
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

1/1 [==============================] - 0s 18ms/step - loss: 185.6075 - accuracy: 0.5556
Accuracy: 55.56


In [ ]:
# make probability predictions with the model
predictions = model.predict(X_test)
print(y_test)
print(predictions)

[[ 2.7e-06 -1.4e-02  5.3e+01]
 [-6.4e-06  1.2e-02  2.9e-01]
 [-2.6e-05  8.7e-02 -1.6e+00]]
[[-0.74569046 -0.0245251   0.34957066]
 [-0.63479203 -0.07109506  0.0433181 ]
 [ 2.159844   -1.3647999   0.832988  ]]
